{application,'Chat',
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{'Chat',[]}},
              {env,[]},
              {modules,[chat_client,chat_server,packet,room_host,room_manager,
                        state_manager,user_manager]}]}.
